import { ShapeParams } from './shapes.js';

export class CodeGenerator {
  generateCode(shapes: ShapeParams[]): string {
    if (shapes.length === 0) {
      return '// No shapes placed yet\n';
    }

    let code = `// Generated by Duud\n`;
    code += `// Canvas size: 800x600\n\n`;
    code += `const canvas = document.getElementById('canvas') as HTMLCanvasElement;\n`;
    code += `const ctx = canvas.getContext('2d')!;\n`;
    code += `canvas.width = 800;\n`;
    code += `canvas.height = 600;\n\n`;

    for (let i = 0; i < shapes.length; i++) {
      const shape = shapes[i];
      code += `// Shape ${i + 1}: ${shape.type}\n`;
      code += this.generateShapeCode(shape);
      code += '\n';
    }

    return code;
  }

  private generateShapeCode(shape: ShapeParams): string {
    switch (shape.type) {
      case 'rectangle':
        return `ctx.fillStyle = '${shape.color}';\nctx.fillRect(${shape.x}, ${shape.y}, ${shape.width}, ${shape.height});`;

      case 'circle':
        return `ctx.fillStyle = '${shape.color}';\nctx.beginPath();\nctx.arc(${shape.x}, ${shape.y}, ${shape.radius}, 0, Math.PI * 2);\nctx.fill();`;

      case 'triangle':
        return `ctx.fillStyle = '${shape.color}';\nctx.beginPath();\nctx.moveTo(${shape.x}, ${shape.y - shape.size});\nctx.lineTo(${shape.x - shape.size}, ${shape.y + shape.size});\nctx.lineTo(${shape.x + shape.size}, ${shape.y + shape.size});\nctx.closePath();\nctx.fill();`;

      case 'line':
        return `ctx.strokeStyle = '${shape.color}';\nctx.lineWidth = ${shape.width};\nctx.beginPath();\nctx.moveTo(${shape.x}, ${shape.y});\nctx.lineTo(${shape.x2}, ${shape.y2});\nctx.stroke();`;

      case 'star':
        const starCode = `ctx.fillStyle = '${shape.color}';\nctx.beginPath();\n`;
        let fullCode = starCode;
        fullCode += `const spikes = 5;\nconst outerRadius = ${shape.radius};\nconst innerRadius = ${shape.radius} * 0.4;\n`;
        fullCode += `for (let i = 0; i < spikes * 2; i++) {\n`;
        fullCode += `  const angle = (i * Math.PI) / spikes - Math.PI / 2;\n`;
        fullCode += `  const r = i % 2 === 0 ? outerRadius : innerRadius;\n`;
        fullCode += `  const px = ${shape.x} + r * Math.cos(angle);\n`;
        fullCode += `  const py = ${shape.y} + r * Math.sin(angle);\n`;
        fullCode += `  if (i === 0) ctx.moveTo(px, py); else ctx.lineTo(px, py);\n`;
        fullCode += `}\n`;
        fullCode += `ctx.closePath();\nctx.fill();`;
        return fullCode;

      default:
        return '// Unknown shape type';
    }
  }
}
